// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParseQuicClient is the client API for ParseQuic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParseQuicClient interface {
	Parse(ctx context.Context, in *ParseQuicRequest, opts ...grpc.CallOption) (*ParseQuicReply, error)
}

type parseQuicClient struct {
	cc grpc.ClientConnInterface
}

func NewParseQuicClient(cc grpc.ClientConnInterface) ParseQuicClient {
	return &parseQuicClient{cc}
}

func (c *parseQuicClient) Parse(ctx context.Context, in *ParseQuicRequest, opts ...grpc.CallOption) (*ParseQuicReply, error) {
	out := new(ParseQuicReply)
	err := c.cc.Invoke(ctx, "/proto.ParseQuic/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseQuicServer is the server API for ParseQuic service.
// All implementations must embed UnimplementedParseQuicServer
// for forward compatibility
type ParseQuicServer interface {
	Parse(context.Context, *ParseQuicRequest) (*ParseQuicReply, error)
	mustEmbedUnimplementedParseQuicServer()
}

// UnimplementedParseQuicServer must be embedded to have forward compatible implementations.
type UnimplementedParseQuicServer struct {
}

func (UnimplementedParseQuicServer) Parse(context.Context, *ParseQuicRequest) (*ParseQuicReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedParseQuicServer) mustEmbedUnimplementedParseQuicServer() {}

// UnsafeParseQuicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseQuicServer will
// result in compilation errors.
type UnsafeParseQuicServer interface {
	mustEmbedUnimplementedParseQuicServer()
}

func RegisterParseQuicServer(s grpc.ServiceRegistrar, srv ParseQuicServer) {
	s.RegisterService(&ParseQuic_ServiceDesc, srv)
}

func _ParseQuic_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseQuicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseQuicServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ParseQuic/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseQuicServer).Parse(ctx, req.(*ParseQuicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseQuic_ServiceDesc is the grpc.ServiceDesc for ParseQuic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseQuic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ParseQuic",
	HandlerType: (*ParseQuicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _ParseQuic_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/parsequic.proto",
}
